### ISSUE TITLE
Invalid pad if size < str.length

### ISSUE THREAD

**Issue by yanickrochon** [wdavidw/node-pad#5]
I was confused at my tests :

```
var value = pad(0, 'foo', { char: ' ' });
// value = "   foo";
```

this is because of the `size = size - string.length`, which is flawed to me... and your CoffeeScript translate 

```
for i in [0 ... size]
```

into

```
for (i = j = 0, ref1 = size; 0 <= ref1 ? j < ref1 : j > ref1; i = 0 <= ref1 ? ++j : --j) {
```

which will treat `size` as an absolute positive value at all times.

Personally, this is why I hate CoffeeScript and any transpiler tricks; nothing beats or will be as efficient as well-crafted plain JavaScript.

In any case, this is not working and should be fixed.

**Comment by Anaphase** [comment]
+1

**Comment by wdavidw** [comment]
May I ask you both to review [this test](https://github.com/wdavidw/node-pad/blob/master/test/pad.coffee#L14-L19) and confirm my understanding of the issue?

**Comment by yanickrochon** [comment]
Looks good. Thanks!

**Comment by wdavidw** [comment]
version 1.0.0 was just published
